# 智慧农业 IoT MQTT TLS 监听器
per_listener_settings true
listener 8883 0.0.0.0
protocol mqtt

allow_anonymous false
password_file /etc/mosquitto/auth/passwd
acl_file /etc/mosquitto/auth/acl

cafile /etc/mosquitto/pki/ca.crt
certfile /etc/mosquitto/pki/server.crt
keyfile /etc/mosquitto/pki/server.key
tls_version tlsv1.2

autosave_interval 60

log_dest syslog
log_type error
log_type warning
log_type notice
connection_messages true
